# Configuration file for Jekyll - https://jekyllrb.com/docs/configuration/


name: Simon Roy
markdown: kramdown
source: 
permalink:
destination:
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - scss/
  - package.json
  - yarn.lock
  - README.md
  - gulpfile.js
  - LICENSE
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  #- dist/
  #- css/
sass:
  sass_dir: ./
    

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


