# Configuration file for Jekyll - https://jekyllrb.com/docs/configuration/


name: Simon Roy
markdown: kramdown
source: ./src/
permalink: pretty

exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  #- js/
  - node_modules/
  - scss/
  - package.json
  - yarn.lock
  - README.md
  - gulpfile.js
  - LICENSE
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - dist/
  - test.html
sass:
  cache: false
  sass_dir: ./css
    

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"


